In [22]:
import numpy as np

In [25]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

NumPy has a data type called "NumPy Arrays." It outputs Vector or Matrix. The syntax is "np.array()"

In [26]:
np_list = np.array([1, 2, 3])nd
np_list

array([1, 2, 3])

In [27]:
np_list = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
np_list

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [28]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [29]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [31]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

行列のサイズが合わない者同士で計算してみる

In [32]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [33]:
array1 * array2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

エラーにはならず，ちゃんと計算されています．計算結果をよくみると，以下の二つのarrayを計算したときと同じになってます．つまり，array1の足りない要素は[1, 2, 3]で自動的に補完されたわけです．これをBroadcastingと呼びます．このBroadcastingのおかげでNumPyは柔軟に行列計算をしてくれます．

Indexing: 

In [34]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
print(ndarray)

[[1 2]
 [3 4]
 [5 6]]


[１個目のindex, ２個目のindex]のようにコンマで繋げるのが一般的

In [41]:
ndarray[0, 1]

2

Slicing（重要）[N:M]としたとき，indexが「N以上M未満」の要素をとってきます. Nが省略されている場合は「最初の要素以上」Mが省略されている場合は「最後の要素以下」になります．

In [42]:
normal_dist_mat = np.random.randn(5, 5)
print(normal_dist_mat)

[[ 0.14262869  0.29947993 -0.16791875  0.64467182  0.49543699]
 [-0.95042392  0.07586615 -0.45056585  0.62939269  1.0851678 ]
 [-0.1146755  -0.92039677 -1.4569242  -0.2823024  -1.14152267]
 [-0.08812099  0.35900119  0.6801078  -0.45258547  0.92676464]
 [-0.15784944 -1.01647764 -0.58597385 -0.3308203   1.21394246]]


In [43]:
print('max is')
print(normal_dist_mat.max())

max is
1.213942456365765


In [44]:
print('standard deviation is')
print(normal_dist_mat.std())

standard deviation is
0.7042849160526273
